visual_inertial:
  ros__parameters:
    T_BC_translation: [0.0, 0.05, 0.0]
    T_BC_quaternion_xyzw: [0.5, -0.5, 0.5, -0.5]

    # Image / camera topics
    input_topic_left: /oak/left/image_rect
    input_topic_right: /oak/right/image_rect
    left/camera_info: /oak/left/camera_info
    right/camera_info: /oak/right/camera_info
    tracks_topic: /tracks
    transport: compressed
    queue_size: 3
    stereo_slop_s: 0.01
    age_penalty: 0.0

    # Frames
    parent_frame_id: odom
    child_frame_id: body

    # VisualInertial core
    target_features: 500
    stereo_epi_eps_y: 1.5
    stereo_disp_min: 3.0
    stereo_disp_max: 255.0
    fb_thr2: 2.25   # (1.5 px)^2 default

    imu_coverage_margin_s: 0.05
    kf_ready_queue_max: 30
    kf_pending_queue_max: 30

    mask_scale: 20

    # PnP tuning
    pnp_iterations_count: 100
    pnp_reproj_error_px: 2.0
    pnp_confidence: 0.999
    pnp_refine_max_iters: 30
    pnp_refine_eps: 1e-6

    # Keyframe policy
    kf_min_dt_s: 0.20
    kf_max_dt_s: 2.00
    kf_min_trans_m: 0.20
    kf_min_rot_deg: 10.0
    kf_min_tracks: 120
    kf_min_pnp_tracks: 80
    kf_min_shared_tracks: 60
    kf_min_shared_ratio: 0.25
    kf_force_on_max_interval: true
    kf_allow_early_on_quality_drop: true

    # IMU preintegration
    imu_gyro_noise_density: 0.01      # rad/s/sqrt(Hz)
    imu_accel_noise_density: 0.10     # m/s^2/sqrt(Hz)
    imu_gyro_bias_rw: 0.001           # rad/s^2/sqrt(Hz)
    imu_accel_bias_rw: 0.01           # m/s^3/sqrt(Hz)
    imu_gravity_mps2: 9.81
    imu_max_buffer_s: 5.0
    imu_keep_anchor: true

optimization_node:
  ros__parameters:
    T_BC_translation: [0.0, 0.05, 0.0]
    T_BC_quaternion_xyzw: [0.5, -0.5, 0.5, -0.5]

    # topics / frames
    keyframe_topic: keyframes
    left_info_topic: oak/left/camera_info
    right_info_topic: oak/right/camera_info
    map_frame_id: map
    odom_frame_id: odom

    tf_pub_rate_hz: 30.0

    # Backend config
    window_size: 15
    stereo_sigma_px: 0.8
    prior_rot_sigma_rad: 0.05
    prior_trans_sigma_m: 0.05
    vel_prior_sigma: 0.1
    bias_acc_prior_sigma: 0.5
    bias_gyro_prior_sigma: 0.1

    use_vo_between: true
    between_rot_sigma_rad: 0.0523599 # 3 deg
    between_trans_sigma_m: 0.05

    use_imu: true

    init_landmarks_from_stereo: true
    prune_unobserved_landmarks: true

    max_keyframe_queue: 30

    # Landmark publishing
    publish_optimized_landmarks: true
    landmark_topic: optimized_landmarks
    landmark_pub_hz: 2.0

    # TF smoothing
    smooth_tau_s: 0.5
    publish_tf_hz: 30.0

    # Landmark cache limits
    lm_cache_max: 6000
    lm_fetch_max: 0  # 0 => fetch all
